### ISSUE TITLE
Chapter 6 broken

### ISSUE THREAD

**Issue by eeqw** [AstroBryGuy/bg1ub#9] opened 2019-03-08 08:39 UTC
Hi once i install this mod and have in the options [Chapter 6 Dialogue Restorations]? <<<< installed the guard at floor 6 that is supposed to take u to jail no longer gives that option he just spam clicks me with the background sound Duhhhhh, so this one needs a fix :)

**Comment by RobinHood70** [comment] 2019-08-05 01:33
I can confirm this. If you go up to the sixth floor _without_ your main character, you're fine to explore. Once the main character's up there, though, the warden talks to you every couple of seconds, saying that you're not allowed to be there.

**Comment by Salk73** [comment] 2020-01-07 21:35
I'd like to know more about this bug and possibly produce a fix for it if AstroBryGuy won't return to modding (I do hope it will).

From what I understand the only real bug here is the Warden initiating dialogue with CHARNAME too often once (s)he goes up to the sixth floor, right?

But once there s(he) is free to explore and talk to Tethoril?

What else is not really working as intended?

Thanks!

**Comment by Gitjas** [comment] 2020-01-18 18:58
The component deactivated the Gatewarden on level 6 and spawns a Watch instead. This creature file is originally only used in teh barracks, but it has a script attached that - amongst others - contains one that lets him initiate dialogue after the PC talked to "Koveras". Since this condition does not close, it leads to the mentioned stutter.
The quickest solution is not to spawn this watch on the 6th level. Another solution would be to create a custom copy that does not have this specific script.

**Comment by Gitjas** [comment] 2020-01-18 19:51
I went for the latter option locally:
COPY_EXISTING ~%tutu_var%watch2.cre~ ~override/ubwatch2.cre~
	WRITE_ASCIIE DEATHVAR	~ubwatch2~ #32
WRITE_EVALUATED_ASCII 0x250 ~~ #8   // Class script: get rid of the watcher.bcs
	BUT_ONLY

**Comment by Gitjas** [comment] 2020-01-18 22:25
fixed in v16.1.

**Comment by Salk73** [comment] 2020-01-19 07:22
Hello Gitjas!

Good job individuating the issue. I was wondering why AstroBryGuy has decided to spawn a Watch on the sixth level of the library. At the moment I cannot verify but are there any other Watches in any other floor?

Thanks!

**Comment by Gitjas** [comment] 2020-01-20 07:53
Yes, it was a quick fix and the whole watch-on-6th-floor situation surely could be improved. I don't know why the watch is there, either, but I did not want to remove him.

You could just pretend the normal accolytes are not expected to dwell on the 6th floor where the high bosses have their quarters or something. :)

**Closed** 2020-11-04 06:26 UTC
